Traceback (most recent call last):
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from myst_nb import glue

def make_axes():
    
    fig, axes = plt.subplots(1, 2, figsize=(9.5,4))
    fig.subplots_adjust(wspace=0.5)
    fig.text(0.5, 0.5, "$A$", fontsize=20, ha="center")
    fig.text(0.5, 0.4, "$\longrightarrow$", fontsize=30, ha="center")
    for ax in axes:
        ax.set_xlim(-2, 2)
        ax.set_ylim(-2, 2)
        ax.set_xticks([-2, -1, 0, 1, 2])
        ax.set_yticks([-2, -1, 0, 1, 2])
        ax.grid()
        ax.set_axisbelow(True)
    
    return fig, axes

def plot_vector(ax, x, y):
    ax.arrow(0, 0, x, y, width=0.03, color="black", length_includes_head=True)
    
def add_text(ax, x, y, s):
    ax.text(x, y, s, fontsize=20)

fig, (ax1, ax2) = make_axes()
plot_vector(ax1, 1, 0)
add_text(ax1, 0.7, -0.4, "$e_1$")
plot_vector(ax1, 0, 1)
add_text(ax1, -0.5, 0.9, "$e_2$") 
plot_vector(ax2, -1, 0)
add_text(ax2, -1, -0.4, "$Ae_1$")
plot_vector(ax2,0, 1)
add_text(ax2, 0.1, 0.8, "$Ae_2$")

glue("la_fig_1", fig, display=False)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
[1;32mC:\Users\NATSCI~1\AppData\Local\Temp/ipykernel_25500/4171418857.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;32mfrom[0m [0mmyst_nb[0m [1;32mimport[0m [0mglue[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [1;32mdef[0m [0mmake_axes[0m[1;33m([0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m    107[0m [1;31m# cbook must import matplotlib only within function[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m    108[0m [1;31m# definitions, so it is safe to import from it here.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 109[1;33m [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0m_api[0m[1;33m,[0m [0m_version[0m[1;33m,[0m [0mcbook[0m[1;33m,[0m [0mdocstring[0m[1;33m,[0m [0mrcsetup[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    110[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcbook[0m [1;32mimport[0m [0mMatplotlibDeprecationWarning[0m[1;33m,[0m [0msanitize_sequence[0m[1;33m[0m[1;33m[0m[0m
[0;32m    111[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcbook[0m [1;32mimport[0m [0mmplDeprecation[0m  [1;31m# deprecated[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\rcsetup.py[0m in [0;36m<module>[1;34m[0m
[0;32m     25[0m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0m_api[0m[1;33m,[0m [0mcbook[0m[1;33m[0m[1;33m[0m[0m
[0;32m     26[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcbook[0m [1;32mimport[0m [0mls_mapper[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 27[1;33m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mcolors[0m [1;32mimport[0m [0mColormap[0m[1;33m,[0m [0mis_color_like[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     28[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0mfontconfig_pattern[0m [1;32mimport[0m [0mparse_fontconfig_pattern[0m[1;33m[0m[1;33m[0m[0m
[0;32m     29[0m [1;32mfrom[0m [0mmatplotlib[0m[1;33m.[0m[0m_enums[0m [1;32mimport[0m [0mJoinStyle[0m[1;33m,[0m [0mCapStyle[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\matplotlib\colors.py[0m in [0;36m<module>[1;34m[0m
[0;32m     49[0m [1;32mfrom[0m [0mnumbers[0m [1;32mimport[0m [0mNumber[0m[1;33m[0m[1;33m[0m[0m
[0;32m     50[0m [1;32mimport[0m [0mre[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 51[1;33m [1;32mfrom[0m [0mPIL[0m [1;32mimport[0m [0mImage[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     52[0m [1;32mfrom[0m [0mPIL[0m[1;33m.[0m[0mPngImagePlugin[0m [1;32mimport[0m [0mPngInfo[0m[1;33m[0m[1;33m[0m[0m
[0;32m     53[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\PIL\Image.py[0m in [0;36m<module>[1;34m[0m
[0;32m    112[0m     [1;31m# Also note that Image.core is not a publicly documented interface,[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m    113[0m     [1;31m# and should be considered private and subject to change.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 114[1;33m     [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0m_imaging[0m [1;32mas[0m [0mcore[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    115[0m [1;33m[0m[0m
[0;32m    116[0m     [1;32mif[0m [0m__version__[0m [1;33m!=[0m [0mgetattr[0m[1;33m([0m[0mcore[0m[1;33m,[0m [1;34m"PILLOW_VERSION"[0m[1;33m,[0m [1;32mNone[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mImportError[0m: DLL load failed: The specified module could not be found.
ImportError: DLL load failed: The specified module could not be found.

