Traceback (most recent call last):
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from myst_nb import glue
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def rayl(X,t,c):
  dxdt = X[1]
  dvdt = -X[0]-c*(X[1]**3 - X[1])
  return [dxdt,dvdt]

t = np.linspace(0,100,10000)

fig,ax=plt.subplots(2,2,figsize=(10,10))

X = odeint(rayl,[0.1,0.1],t,args=(-1,))
ax[0].plot(X[:,0],X[:,1],'r')
ax[0].set_title('c=-1')

X = odeint(rayl,[0.1,0.1],t,args=(0,))
ax[1].plot(X[:,0],X[:,1],'r')
ax[1].set_title('c=0')

X = odeint(rayl,[0.1,0.1],t,args=(1,))
ax[2].plot(X[:,0],X[:,1],'r')
ax[2].set_title('c=1')

for i in ([0.1,0.1],[-0.1,-0.1],[0.1,-0.1],[-0.1,0.1]):
  X = odeint(rayl,i,t,args=(2,))
  ax[3].plot(X[:,0],X[:,1],'r')
ax[3].set_title('c=2')

glue("rayl_fig", fig, display=False)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32mC:\Users\ELLAME~1\AppData\Local\Temp/ipykernel_12020/2310704776.py[0m in [0;36m<module>[1;34m[0m
[0;32m     14[0m [1;33m[0m[0m
[0;32m     15[0m [0mX[0m [1;33m=[0m [0modeint[0m[1;33m([0m[0mrayl[0m[1;33m,[0m[1;33m[[0m[1;36m0.1[0m[1;33m,[0m[1;36m0.1[0m[1;33m][0m[1;33m,[0m[0mt[0m[1;33m,[0m[0margs[0m[1;33m=[0m[1;33m([0m[1;33m-[0m[1;36m1[0m[1;33m,[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 16[1;33m [0max[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mX[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m[1;36m0[0m[1;33m][0m[1;33m,[0m[0mX[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m[1;36m1[0m[1;33m][0m[1;33m,[0m[1;34m'r'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     17[0m [0max[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m.[0m[0mset_title[0m[1;33m([0m[1;34m'c=-1'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     18[0m [1;33m[0m[0m

[1;31mAttributeError[0m: 'numpy.ndarray' object has no attribute 'plot'
AttributeError: 'numpy.ndarray' object has no attribute 'plot'

